### ISSUE TITLE
似乎不支持params为Array的Attribute构造方法

### ISSUE THREAD

**Issue by xzaxzaazx** [labbbirder/DirectRetrieveAttribute#4]
error LB0001: fail to generate direct retrieve attributes for assembly , reason: TypedConstant is an array. Use Values property.	   at Microsoft.CodeAnalysis.TypedConstant.get_ValueInternal()
	   at Microsoft.CodeAnalysis.TypedConstant.get_Value()
	   at DirectAttribute.sg.Extensions.<>c__11`1.<ToAttribute>b__11_0(TypedConstant a)
	   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
	   at DirectAttribute.sg.Extensions.ToAttribute[T](AttributeData data)
	   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
	   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
	   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
	   at DirectAttribute.sg.Extensions.GetAttribute[T](ISymbol type)
	   at DirectAttribute.sg.Generator.<Execute>g__VisitSymbol|4_1(ISymbol symbol, <>c__DisplayClass4_0& )
	   at DirectAttribute.sg.Generator.Execute(GeneratorExecutionContext context)

**Comment by labbbirder** [comment]
This should be fixed since 7693694dd1557c9a80b926049837a05242af7a6c
